name: inexor
version: 0.9.0
summary: Inexor - Community fork of the Cube 2: Sauerbraten game.
description: Inexor is a fork of the open-source First-Person-Shooter Cube 2: Sauerbraten, a fast-paced shooting game featuring an ingame map editor.
  In contrast to Sauerbraten, Inexor adds a lot of functionality and strives to stay open to improvements and suggestions.
  The goal of this project is to be more flexible and create an environment where development is easy, fast and where creativity can prosper.

apps:
  inexor:
    command: bin/inexor

parts:
  client:
    stage-packages:
      - git
      - cmake
      - build-essential
      - libgl1-mesa-dev
      - doxygen
      - libfontconfig1
      - libfreetype6
      - libnss3
      - libxcomposite1
      - libxtst6
      - libgconf-2-4
      - libcups2
      - libcairo2
      - libpango-1.0-0
      - libpangocairo-1.0-0
    plugin: conan
    source: https://github.com/inexor-game/code.git # add a release branch when 0.9 is released
    missing: true
